# Generated by Django 3.1 on 2020-12-14 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food1', '0002_auto_20201210_1546'),
    ]

    operations = [
        migrations.AlterField(
            model_name='burger',
            name='priceL',
            field=models.DecimalField(decimal_places=2, max_digits=6),
        ),
        migrations.AlterField(
            model_name='burger',
            name='priceM',
            field=models.DecimalField(decimal_places=2, max_digits=6),
        ),
        migrations.AlterField(
            model_name='pizza',
            name='priceL',
            field=models.DecimalField(decimal_places=2, max_digits=6),
        ),
        migrations.AlterField(
            model_name='pizza',
            name='priceM',
            field=models.DecimalField(decimal_places=2, max_digits=6),
        ),
    ]
